apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: hello-html

---
apiVersion: v1
kind: Service
metadata:
  name: hello-nginx-svc
spec:
  selector:
    app: hello-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer # Note: For a single-node k3s, this will likely provision a local port
                   # You might need to access it via the node's IP and a high port.
                   # For cloud providers with LoadBalancer support, it will provision a cloud LB.

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello World!</title>
    </head>
    <body>
      <h1>Hello World from Nginx!</h1>
    </body>
    </html>
